[context.branch-deploy.environment]
  REACT_APP_LEDGER_CHAIN_ID = "anoma-masp-1.5.32ccad5356012a"
  REACT_APP_LEDGER_URL = "https://d3brk13lbhxfdb.cloudfront.net/anoma-masp-1.5.32ccad5356012a7"
  REACT_APP_FAUCET = "atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3"

[context.deploy-preview.environment]
  REACT_APP_LEDGER_CHAIN_ID = "anoma-masp-1.5.32ccad5356012a"
  REACT_APP_LEDGER_URL = "https://d3brk13lbhxfdb.cloudfront.net/anoma-masp-1.5.32ccad5356012a7"
  REACT_APP_FAUCET = "atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3"

[context.production.environment]
  REACT_APP_LEDGER_CHAIN_ID = "anoma-masp-1.5.32ccad5356012a"
  REACT_APP_LEDGER_URL = "https://d3brk13lbhxfdb.cloudfront.net/anoma-masp-1.5.32ccad5356012a7"
  REACT_APP_FAUCET = "atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3"
  