name: Deploy wallet preview to netlify at PR and pushes to it
on:
  push:
    branches:
      - main
    paths:
      - "anoma-wallet/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0

      - name: Install dependencies
        working-directory: ./anoma-wallet
        run: npm install

      - name: build the site
        working-directory: ./anoma-wallet
        run: CI=false npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: "./anoma-wallet/build"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Merged PR ${{ github.event.number }} to main"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN_WALLET_PREVIEW }}
          NETLIFY_SITE_ID: 2380782e-9b20-477a-bc27-b4e9d05e16f3
      - name: Slack Notification
        run: |
          curl --header "Content-Type: application/json" \
          --request POST \
          --data '{"message":"https://wallet-preview-heliax-dev.netlify.app"}' \
          ${{ secrets.SLACK_WEBHOOK_WALLET_RELEASE }}
